name: Publish to Packagist

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Packagist

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, session, simplexml, tokenizer, xml, xmlreader, xmlwriter
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run tests before publishing
        run: composer test

      - name: Run code quality checks
        run: composer check

      - name: Publish to Packagist
        run: |
          composer config http-basic.repo.packagist.com token ${{ secrets.PACKAGIST_TOKEN }}
          composer publish --no-interaction
        env:
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }} 